# Generated by Django 4.0.5 on 2022-06-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_choice_college_alter_choice_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='subject',
            new_name='mail',
        ),
    ]
